name: flutter_todo_app
description: A simple TODO application for Cross platfrom course



version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  parse_server_sdk_flutter: ^7.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/